# Generated by Django 4.0.5 on 2023-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTABLE'), ('1', 'ADMINISTATIVO'), ('2', 'GERENTE'), ('3', 'GESTOR'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
