# Generated by Django 4.0.5 on 2023-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTABLE'), ('1', 'ADMINISTRATIVO'), ('2', 'GERENTE'), ('3', 'GESTOR'), ('4', 'OTRO')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
